version: "3"
services:
  back:
    container_name: infinibrains
    image: node:lts
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "1337:1337"
    links:
      - postgres
    command: |
      npm install
      npm run setup
      npm run dev
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - "8081:8080"

volumes:
  postgres:
    driver: local
