version: "3.8"

name: game-guild

networks:
  game-guild-network:

services:
  api:
    build:
      dockerfile: DockerfileApi
    container_name: api
    image: game-guild-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    links:
      - postgres
    # expose postgres to api
    networks:
      - game-guild-network

  web:
    build:
      dockerfile: DockerfileWeb
    container_name: web
    image: game-guild-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - game-guild-network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - game-guild-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - postgres
    networks:
      - game-guild-network

volumes:
  postgres:
    driver: local
