version: "3"
services:
  back:
    container_name: backend
    restart: always
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  front:
    container_name: frontend
    restart: always
    build: ./front
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    links:
      - back
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    driver: local
