version: "3.8"

name: game-guild

services:
  api:
    build:
      context: ./services/api
    container_name: api
    image: game-guild-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  web:
    build:
      context: ./services/web
    container_name: web
    image: game-guild-api
    restart: always
    ports:
      - "8081:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: game-guild
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    driver: local
