version: "3"
services:
  app:
    container_name: infinibrains
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - "8081:8080"

volumes:
  postgres:
    driver: local
