export default {
    // NEXT_PUBLIC_STRAPI_API_TOKEN: process.env.NEXT_PUBLIC_STRAPI_API_TOKEN || 'your-api-token',
    NEXT_PUBLIC_PAGE_LIMIT: process.env.NEXT_PUBLIC_PAGE_LIMIT || 6,
    NEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN: process.env.NEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN || 'your-form-submission-token',
    NEXT_PUBLIC_STRAPI_API_URL: process.env.NEXT_PUBLIC_STRAPI_API_URL || 'http://127.0.0.1:1337'
}